site_name: JASON VACHIER | Documentation aggreg.py


extra_css:
  - css/night-owl.css 

extra_javascript:
  - js/highlight.min.js  
  - js/highlight-init.js


nav:
  - Introduction:
    - "Présentation" : "index.md"
    
    - "Le guide d'installation et de paramétrage" : "Etape1.md"

    - "aggreg.py" : "AggregPy.md"

    - "style.css" : "StyleCss.md"



theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/moon-waxing-crescent
        name: Switch to dark mode
      primary: light blue
      accent: blue
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
      primary: light blue
      accent: lime